# base layer - starting from an existing image
FROM python:3.9

# instruction layer - where we will start in the container
WORKDIR /app

# instruction layer - copies everything from this folder in host system into /app
COPY . .

# instruction layer - installing packages (runs bash command)
RUN pip install matplotlib pandas

# instruction layer - bash command to run when container is spun up
CMD [ "python", "/app/src/os_data.py" ]